### ISSUE TITLE
[ERROR] EnvironmentConfiguration.ChangeEnvironment

### ISSUE THREAD

**Issue by brunoportess** [pagseguro/pagseguro-sdk-dotnet#22]
Em um projeto aspnet core 2.0 WebAPI da erro já no início daexecução.
Utilizei o código de exemplo do próprio repositório.
![image](https://user-images.githubusercontent.com/15960693/33616739-ee61ce86-d9c4-11e7-9d47-037fb19d6c7f.png)

**Comment by TheNullable** [comment]
Bruno, infelizmente o SDK para o .NET não tem como target compilar para o .NET Core ou Standard, somente no nativo (.NET Framework).
