### ISSUE TITLE
Previsão de biblioteca .Net Core?

### ISSUE THREAD

**Issue by taxpayer** [pagseguro/pagseguro-sdk-dotnet#26]
Há alguma previsão de lançarem a versão da biblioteca para .Net Core, de preferência para a última versão?

**Comment by lucksma96** [comment]
#18 há quase um ano (se não mais) aguardando ser aceito

**Comment by taxpayer** [comment]
@lucksma96 Sou só eu, ou você também acha que o PagSeguro não dá a mínima para as suas bibliotecas e documentação online?

Acho impressionante uma empresa que é referência de pagamento online para muitas pessoas e empresas do Brasil ter esse tipo de descaso com os desenvolvedores que se propõem a fazer qualquer tipo de integração com suas soluções.

**Comment by lucksma96** [comment]
Concordo e me pergunto como uma empresa dessas consegue se dar bem no mercado.

Uma biblioteca dessas abandonada, e uma documentação mal escrita e confusa. Até amadores conseguem fazer melhor.

**Comment by cigano** [comment]
Atualmente, sou o mantenedor do pacote NuGet.

Se quiserem, posso fazer um fork deste repositório e lançamos um pacote
NuGet para o Core também.

**Comment by taxpayer** [comment]
@cigano Você é ligado ao PagSeguro ou mantem por iniciativa pessoal?

Pergunto porque realmente me espanta o tratamento que o PagSeguro dá à sua biblioteca. É uma empresa grande, o descaso com que tratam isso é impressionante. As issues requisitando esta versão estão aí já há bastante tempo também. Seria interessante ter uma posição oficial do PagSeguro ou de alguém respondendo por eles, daí a minha pergunta.

Em relação à sua pergunta, acho que não somente nós, mas diversos desenvolvedores seriam beneficiados com este movimento. O Core já deixou de ser uma promessa há muito tempo, já está na linha de produção de diversas empresas.

**Comment by cigano** [comment]
Iniciativa pessoal mesmo.

Tive os mesmos problemas que vocês pra resolver outro problema muito
simples: não usar um arquivo XML em separado na configuração do ambiente.
Contei toda a história aqui:
https://github.com/DesignLiquido/pagseguro-dotnet#pre%C3%A2mbulo

Se toparem me ajudar, vamos para o fork.

**Comment by marciogoularte** [comment]
A verdade é que eles dão mais ênfase a bibliotecas de outras tecnologias mais populares que .NET.
