### ISSUE TITLE
Checkout Transparente

### ISSUE THREAD

**Issue by gabrielfava** [pagseguro/pagseguro-sdk-dotnet#28]
Existe previsão para adição da funcionalidade transparente igual nas bibliotecas JAVA, php ?

**Comment by fernandomr** [comment]
Gabriel, também tive essa dúvida!
Te adianto que o checkout transparente funciona sim nessa lib.
Nos exemplos do repositório está na pasta "Direct"

**Comment by gabrielfava** [comment]
Ah legal, show de bola, vou dar uma olhada.  Valeu amigo

**Comment by luiz-merante** [comment]
@fernandomr você já tentou fazer o checkout transparente sem frete? comigo não funciona!

**Comment by fernandomr** [comment]
@luiz-merante desculpe a demora em responder.
Sim, pelo menos em testes pra mim deu certo o checkout transparente sem frete pois os produtos que trabalhei eram serviços.

**Comment by aemsoftwarearacatuba** [comment]
> @luiz-merante desculpe a demora em responder.
> Sim, pelo menos em testes pra mim deu certo o checkout transparente sem frete pois os produtos que trabalhei eram serviços.

como você fez para gerar o Hash do Sender?

**Comment by fernandomr** [comment]
> 
> 
> > @luiz-merante desculpe a demora em responder.
> > Sim, pelo menos em testes pra mim deu certo o checkout transparente sem frete pois os produtos que trabalhei eram serviços.
> 
> como você fez para gerar o Hash do Sender?

Através da lib JS do browser, se me lembro bem.
