### ISSUE TITLE
response answered with null value no Register

### ISSUE THREAD

**Issue by edgarrc** [pagseguro/pagseguro-sdk-dotnet#30]
## Comportamento esperado
Registro realizado ou retorno do motivo do não registro detalhando o problema.

## Comportamento atual
Gerando exceção ao executar o Register, sem qualquer esclarecimento do motivo.

## Ambiente (produção, sandbox)
Sandbox

## Passos para reproduzir o bug
Ao chamar o Register, obtenho: response answered with null value

```
PaymentRequest payment = new PaymentRequest();
[...]
Uri paymentRedirectUri = null;
paymentRedirectUri = payment.Register(credentials);
```
Este código já chegou a funcionar muitas vezes, simplesmente repeti o teste nesse momento e passou a reproduzir esse erro.

## Descrição Detalhada

O Stracktrace indica a exception em Uol.PagSeguro.Domain.PaymentRequest.Register:

```
   at Uol.PagSeguro.Util.HttpURLConnectionUtil.CreatePagSeguroServiceException(HttpWebResponse response) in D:\Documents\GitHub\pagseguro-dotnet\source\Uol.PagSeguro\Util\HttpURLConnectionUtil.cs:line 47
   at Uol.PagSeguro.Service.PaymentService.CreateCheckoutRequest(Credentials credentials, PaymentRequest payment) in D:\Documents\GitHub\pagseguro-dotnet\source\Uol.PagSeguro\Service\PaymentService.cs:line 76
   at Uol.PagSeguro.Domain.PaymentRequest.Register(Credentials credentials) in D:\Documents\GitHub\pagseguro-dotnet\source\Uol.PagSeguro\Domain\PaymentRequest.cs:line 263
   at xxxxxPagamentoService.CriarPagamentoxxxxx 
``

## Possível solução
Pesquisando sobre o assunto, existem muitas sugestões de acréscimo do tempo de timeout no xml (que foi feito, mas não é o caso, ocorre instantaneamente), outros sugerem possível erro de DNS, que também não é o caso (testado em diversas redes, diversos ambientes).

**Comment by arthurhfuzinatto** [comment]
Resolvido aqui com a alteração da versão do .NET framework e alteração do protocolo para TLS 1.2

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

**Comment by edgarrc** [comment]
@arthurhfuzinatto Obrigado, neste caso, esta solução já havia sido tentada e não obtive sucesso

**Comment by seguel** [comment]
Bom dia estou com mesmo problema, ate dezembro/18 funcionava sem problemas, e agora da esse erro sendo que nada foi alterado, e também não passa de 10 segundos, e testes tanto no servidor locaweb como local.

**Comment by seguel** [comment]
Alguém conseguiu descobrir o por que?

**Comment by david-inacio** [comment]
Também estou com esse problema...

**Comment by david-inacio** [comment]
Cheguei nesse trecho, onde o método GetHttpURLConnection submete o email e o token;

![image](https://user-images.githubusercontent.com/48891735/54885072-261bfb00-4e57-11e9-8ed6-b9a39bdd3686.png)

porem na exceção retorna o erro:
A solicitação foi anulada: não foi possível criar o canal seguro de SSL/TLS

Fiz um teste com o postman e o retorno acontece direitinho... não sei porque pelo sdk não funciona....

**Comment by seguel** [comment]
Bom dia, no meu caso a mensagem parou após implementar a linha (após o post do arthurhfuzinatto) 

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

**Comment by edgarrc** [comment]
O @arthurhfuzinatto já havia sugerido acima, não resolveu no meu caso.

Sendo bem realista o último commit de biblioteca deles foi ha 3 anos... então não espere resposta.

**Comment by amazoniacentral** [comment]
Há um erro no arquivo HttpUrlConnectionUtil da biblioteca do PagSeguro. Pelo nuget não tem como corrigir mas se baixar Aki do Git basta acessar o arquivo que fica na pasta Útil e ir no método GetHttpUrlConnection

Dentro do método tem um chamado para a API do PagSeguro o (HttpWebRequest)WebRequest.Create(urlPath)
O erro está aqui porque está fazendo a requisição limpa sem mandar os parâmetros que estão na string query.

Corrige colocando a string query para completar a URL
(HttpWebRequest)WebRequest.Create(urlPath+"?"+query)

Pronto agora a requisição vai com a URL completa
