### ISSUE TITLE
Erro ao testar exemplos , sempre mensagem : A solicitação foi anulada: Não foi possível criar um canal seguro para SSL/TLS.

### ISSUE THREAD

**Issue by eduardolima0606** [pagseguro/pagseguro-sdk-dotnet#37]
_Este relatório deve ser usado **APENAS** para reportar bugs_

## Comportamento esperado
Exemplo Authorization deveria autorizar ou voltar mensagem de não autorizado(as padrões)

## Comportamento atual
Sistema dá sempre mensagem de : A solicitação foi anulada: Não foi possível criar um canal seguro para SSL/TLS.

## Passos para reproduzir o bug
Abrir projeto Authorization/ CreateAuthorization
Executar o mesmo.
## Descrição Detalhada
ao debugar o projeto.
na linha : return (HttpWebResponse)request.GetResponse();
dá o erro : A solicitação foi anulada: Não foi possível criar um canal seguro para SSL/TLS.

Já fiz todos os passo sugeridos na comunidade.
1 - Colocar  : ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls;
pois colocar SecurityProtocolType.Tls12, não é possivel no projeto.
2- Aumentar o tempo limite para conexão.

Teste realizado em Windows10 , .Net = 4.7.2

**Comment by leobaccili** [comment]
Coloca assim:
ServicePointManager.SecurityProtocol = (SecurityProtocolType)192 | (SecurityProtocolType)768 | (SecurityProtocolType)3072;

**Comment by renatogava** [comment]
Alguma resolucão para esse problema? Está ocorrendo comigo também. Já tentei as solucões acima, não deu certo.
