### ISSUE TITLE
[ERRO] Checkout Transparente

### ISSUE THREAD

**Issue by luiz-merante** [pagseguro/pagseguro-sdk-dotnet#40]
Quando vou criar a transaction do checkou transparente, ele só funciona se tiver shipping, caso eu venda um produto sem shipping, não tem o campo shippingRequired na classe Shipping para eu poder deixar falso e não enviar o shipping, alguém sabe como eu faria pra fazer uma transaction sem shipping?

**Comment by gabrielscr** [comment]
como vc fez pra gerar o token do cartão?
